### ISSUE TITLE
Support OAuth2

### ISSUE THREAD

**Issue by marekjagielski** [tomek199/elo-rating#154]
As an Administrator of local instance I would like easy authentication in my organization by integrate with corporate OAuth2 provider.

**Comment by tomek199** [comment]
Hi Marek, 
The **elo-rating** project is deprecated and will not be longer developed. 
Instead of, please take a look on my new project https://github.com/tomek199/RankMe which is going to be replacement for elo-rating. **RankMe** is not fully functional yet, but it is under development. There is already task created to implement OAuth2 authentication https://github.com/tomek199/RankMe/issues/144 
Regards 😄 
Tomek
