### ISSUE TITLE
Add more installation details to the readme

### ISSUE THREAD

**Issue by mdanielak** [tomek199/elo-rating#95]
Hello,
I'd like to use your project for the same purposes (pingpong at the work place) but readme is not helpfull enough. Please expand readme for needed prerequisites, steps and information how to setup the whole project on the server.
Secondly, should I also use your other project https://github.com/tomek199/elo-rating-core? I didn't have time to really dig in into it.

Thanks,
Maciek

**Comment by tomek199** [comment]
Hi @mdanielak, 
For now you need also my second project _elo-rating-core_ because there is server-side module for this app. I have a plan to merge this two projects into one, to make deploying new application instance easier. After that I can update _readme_ by missing informations. I think I'll do that within next two weeks, so please be patient 😉. 

Thanks for the feedback
Tomek
